//! Transformer preset for Obfuscator.io / javascript-obfuscator.
//!
//! Includes the full default transformer set plus specialized transforms
//! for patterns generated by Obfuscator.io:
//!
//! - String array decoding (atob, custom base64 alphabets)
//! - String array rotation
//! - Control flow array flattening
//! - Proxy function inlining (included in defaults)
//! - Dead code injection removal (included in defaults)

use crate::transformer::Transformer;
use crate::transforms;

/// Returns transformers targeting Obfuscator.io patterns.
pub fn transformers() -> Vec<Box<dyn Transformer>> {
    let mut result = Vec::new();

    // Obfuscator.io-specific transforms run first.
    result.push(
        Box::new(transforms::obfuscator_io::StringArrayDecoderTransformer::default())
            as Box<dyn Transformer>,
    );
    result.push(
        Box::new(transforms::obfuscator_io::StringArrayRotationTransformer::default())
            as Box<dyn Transformer>,
    );
    result.push(
        Box::new(transforms::obfuscator_io::ControlFlowArrayTransformer::default())
            as Box<dyn Transformer>,
    );

    // Then all general-purpose transforms.
    result.extend(transforms::default_transformers());

    result
}
