//! Transforms that simplify expressions and statements.

mod bitwise_simplification_transformer;
mod block_normalization_transformer;
mod comma_transformer;
mod control_flow_transformer;
mod declaration_merge_transformer;
mod function_declaration_transformer;
mod global_alias_simplification_transformer;
mod logical_to_if_transformer;
mod member_transformer;
mod sequence_statement_transformer;
mod ternary_to_if_transformer;
mod var_hoisting_transformer;
mod variable_declaration_split_transformer;

pub use bitwise_simplification_transformer::BitwiseSimplificationTransformer;
pub use block_normalization_transformer::BlockNormalizationTransformer;
pub use comma_transformer::CommaTransformer;
pub use control_flow_transformer::ControlFlowTransformer;
pub use declaration_merge_transformer::DeclarationMergeTransformer;
pub use function_declaration_transformer::FunctionDeclarationTransformer;
pub use global_alias_simplification_transformer::GlobalAliasSimplificationTransformer;
pub use logical_to_if_transformer::LogicalToIfTransformer;
pub use member_transformer::MemberTransformer;
pub use sequence_statement_transformer::SequenceStatementTransformer;
pub use ternary_to_if_transformer::TernaryToIfTransformer;
pub use var_hoisting_transformer::VarHoistingTransformer;
pub use variable_declaration_split_transformer::VariableDeclarationSplitTransformer;
